language: c
sudo: false

env:
  - TARGET_ARCH=x86_64

script:
  - make

deploy:
  - provider: releases
    on:
      tags: true
      branch: master
    file_glob: true
    file: build/artifacts/*
    skip_cleanup: true
    overwrite: true
    api_key:
      secure: "RopUuXJAmy5fdnQv30NDvRzB/GpJBMNyIcqT3H1l1i/nnbSwqKTmqWDipF4qHe2uoxauwgYdb3vvHg0KA/Z3cowFBrywmtDXzk4kNYv/ayfyDuFwzdjgFW1BRlfz17Q6W9rjt3R+kHpveY0gYd/crKQv8yQVYLUrQWkejICyMhIKa6UZuE5dorHvlEtv3K+kA8QqVE2GS12rxQkrfUmSSPZ9PoaZ2OdWLtIk9CvS23FKFjVDNwjJ2CVpjItCJ3QFG6IVYvQHNNxe9xn6wR9kLwX6mBG0FFMzEpPfJj47zlAH5EOiEkd5Q4jfj+Q8TtuZbVefssrzuBplen/sjqs6vzrR60G/jGU7BnE2y8GO5VM255LsCupZrnSaRHh/Bv6lC6nafUv1H4/D8AWXW24cQj2tmIxQlSLVxwqShbBnRqE+SD/2APKN6sZKeRwnr9XOmyoSfhpBGMYFx2jrbU8lt2T44gZGxXA+uCg7T+Ykgygx/i62EBE4lu9h0XItj/3ITB7jmKKx+daumXXVU5Uswem3u+xTxOAp/e7g/2ILUTUp4qgYt4D8PZDrDIAp6zrQgwnqvUytF4G+osw8VX3zTcaz5E8UF9U+sh1KE9YsZTvVMG5EqoALl776QsJoJyD7/Uorr4kW2GrvusYLwhrhIMomfs1wPzjIB3HemylfzL8="

cache:
  directories:
    - build

# vim: expandtab sw=2 sts=2
